## 07. 원근 변환

In [3]:
import cv2
import numpy as np

CARD = 'images/card.jpg'

In [6]:
import cv2
import numpy as np

img = cv2.imread(CARD)

width , height = 600, 400

# 변형할 지점 선택 : 시계방향
src = np.array([[54,261],[981,128],[1213,560],[194,735]], dtype=np.float32) #왼쪽 위부터 시계방향으로돌아가며

# 결과물 출력할 형태 : 시계방향
dst = np.array([[0,0],[width,0],[width,height],[0,height]], dtype=np.float32)

# 원근을 변형하기 위한 matrix생성
mat = cv2.getPerspectiveTransform(src,dst)#(변형할소스,결과물 출력할 형태)
print(mat)

# img를 mat에 의해 변환
result = cv2.warpPerspective(img, mat,(width,height))#(원본,변환하기위한,출력될(너비,높이))


cv2.imshow('img',img)
cv2.imshow('perspective',result)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 6.28270120e-01 -1.85565014e-01  1.45058823e+01]
 [ 1.38283394e-01  9.63824859e-01 -2.59025592e+02]
 [-2.25609902e-05  2.65181603e-04  1.00000000e+00]]


### 실습1. 이미지 원근 변환

In [21]:
TOWER = 'images/singer.jpg'
img = cv2.imread(TOWER)

width , height = 500, 750

# 변형할 지점 선택 : 시계방향
src = np.array([[239,57],[453,65],[183,619],[25,619]], dtype=np.float32) #왼쪽 위부터 시계방향으로돌아가며

# 결과물 출력할 형태 : 시계방향
dst = np.array([[0,0],[width,0],[width,height],[0,height]], dtype=np.float32)

# 원근을 변형하기 위한 matrix생성
mat = cv2.getPerspectiveTransform(src,dst)#(변형할소스,결과물 출력할 형태)
# print(mat)

# img를 mat에 의해 변환
result = cv2.warpPerspective(img, mat,(width,height))#(원본,변환하기위한,출력될(너비,높이))


cv2.imshow('img',img)
cv2.imshow('perspective',result)
cv2.waitKey(0)
cv2.destroyAllWindows()