## 13. 얼굴 인식

In [51]:
import cv2
IU = 'images/IU.jpg'
FAMILY = 'images/family.jpg'
DOG = 'images/dog.jpg'
CROSS = 'images/cross.jpg'

In [22]:
face_cascade = cv2.CascadeClassifier('cascade/haarcascade_frontalface_default.xml')
# eye_cascade = cv2.CascadeClassifier('cascade/haarcascade_eye.xml')

img = cv2.imread(FAMILY)
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
faces = face_cascade.detectMultiScale(
    gray, scaleFactor = 1.1, minNeighbors = 10, minSize = (20,20)
)
# print(faces)

for face in faces:
    x, y, width, height = face
    cv2.rectangle(img, (x,y), (x+width, y+height), (0,255,0), 4)


cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[620 245 111 111]
 [424 127  79  79]
 [563 393  99  99]
 [421 262 105 105]]


In [54]:
face_cascade = cv2.CascadeClassifier("cascade/haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier("cascade/haarcascade_eye.xml")
img = cv2.imread(CROSS)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
faces = face_cascade.detectMultiScale(
    gray, scaleFactor=1.1, minNeighbors=10, minSize=(20,20)
)
eyes = eye_cascade.detectMultiScale(
    gray, scaleFactor=1.1, minNeighbors=2, maxSize=(50,50)
)
if len (faces):
    for face in faces:
        x, y, width, height = face
        cv2.rectangle(img, (x,y), (x+width, y+height), (0,255,0), 4)
if len (eyes):
    for eye in eyes:
        x, y, width, height = eye
        cv2.rectangle(img, (x,y), (x+width, y+height), (255,0,255), 3)
cv2.imshow("img", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 동영상에서 얼굴 인식 트랙바 version)

In [4]:
# 얼굴인식
import cv2
face_cascade = cv2.CascadeClassifier('cascade/haarcascade_frontalface_default.xml')
road_path = 'videos/person2.mp4'
cap = cv2.VideoCapture(road_path)
fps = cap.get(cv2.CAP_PROP_FPS)

name = 'video'
cv2.namedWindow(name)
cv2.createTrackbar("minSize",name, 0, 200, lambda x:x)
cv2.createTrackbar("maxSize",name, 0, 1000, lambda x:x)

while cap.isOpened():
    threshold1 = cv2.getTrackbarPos('minSize',name)
    threshold2 = cv2.getTrackbarPos('maxSize',name)
    
    ret, frame = cap.read()
    
    if not ret:
        break
    
    faces = face_cascade.detectMultiScale(
    frame, scaleFactor = 1.1, minNeighbors = 5, minSize = (threshold1,threshold1), maxSize=(threshold2,threshold2)
    )

    if len(faces):
        for x, y, w, h in faces:
            cv2.rectangle(frame, (x,y), (x+w,y+h), (0,255,0), 4)
            
    frame = cv2.resize(frame, None, fx=0.5, fy=0.5)
    cv2.imshow(name,frame)
    
    if cv2.waitKey(int(1000/fps)) == ord("q"):
        break

cap.release()
cv2.destroyAllWindows()


### 동영상에서 얼굴 인식

In [5]:
# 얼굴인식
import cv2
face_cascade = cv2.CascadeClassifier('cascade/haarcascade_frontalface_default.xml')
road_path = 'videos/person2.mp4'
cap = cv2.VideoCapture(road_path)
fps = cap.get(cv2.CAP_PROP_FPS)

while cap.isOpened():
    
    ret, frame = cap.read()
    
    if not ret:
        break
    
    faces = face_cascade.detectMultiScale(
    frame, scaleFactor = 1.1, minNeighbors = 5, minSize = (30,30), maxSize=(2000,2000)
    )

    if len(faces):
        for x, y, w, h in faces:
            cv2.rectangle(frame, (x,y), (x+w,y+h), (0,255,0), 4)
            
    frame = cv2.resize(frame, None, fx=0.5, fy=0.5)
    cv2.imshow('video',frame)
    
    if cv2.waitKey(int(1000/fps)) == ord("q"):
        break

cap.release()
cv2.destroyAllWindows()


### 실습1. 캠화면에 적용

In [7]:
# 얼굴인식
import cv2
face_cascade = cv2.CascadeClassifier("cascade/haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier("cascade/haarcascade_eye.xml")

cap = cv2.VideoCapture(0)
if not cap.isOpened():
    exit()
    
# list_1 = [1,2,3]
# list_2 = ['r','s','d']
# print(list(zip(list_1,list_2)))
SCALE = 2
COLOR = (255,255,255)
THICKNESS = 1

while True:
    ret,frame = cap.read()
    if not ret:
        break
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=10, minSize=(30,30))
    eyes = eye_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, maxSize=(30,30))
    objects, weights = face_cascade.detectMultiScale2(gray, scaleFactor=1.1, minNeighbors=5, minSize=(20, 20))
    
    if len(faces):
        for (x, y, w, h),weight in zip(faces,weights):
            # if weight > 50:
                cv2.rectangle(frame, (x,y), (x+w,y+h), (0,255,0), 4)
                cv2.putText(frame, f"face: {weight}", (x,y), cv2.FONT_HERSHEY_PLAIN, SCALE,COLOR,THICKNESS)
    if len(eyes):
        for (x, y, w, h),weights in zip(eyes,weights):
            cv2.rectangle(frame, (x,y), (x+w,y+h), (0,255,0), 4)
            cv2.putText(frame, "eye", (x,y), cv2.FONT_HERSHEY_PLAIN, SCALE,COLOR,THICKNESS)
            
    cv2.imshow("Camera",frame)
    if cv2.waitKey(1) == ord("q"):
        break
        
cap.release()
cv2.destroyAllWindows()

### 연습

In [9]:
face_cascade = cv2.CascadeClassifier("cascade/haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier("cascade/haarcascade_eye.xml")

cap = cv2.VideoCapture(0)

if not cap.isOpened():
  exit()

while True:
  ret, frame = cap.read()

  if not ret:
    break
  
  gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

  faces, weights = face_cascade.detectMultiScale2(
    gray, scaleFactor=1.1, minNeighbors=10
  )
  eyes = eye_cascade.detectMultiScale(
    gray, scaleFactor=1.1, minNeighbors=5
  )

  if len(faces):
    for (x,y,w,h), weight in zip(faces, weights):
        cv2.rectangle(frame, (x,y), (x+w,y+h), (0,255,0), 4)
        cv2.putText(frame, f"face: {weight}", (x,y), cv2.FONT_HERSHEY_PLAIN, 1.5, (255,255,255), 1)

  if len(eyes):
    for (x,y,w,h), weight in zip(eyes, weights):
      cv2.rectangle(frame, (x,y), (x+w,y+h), (255,0,0), 3)
      cv2.putText(frame, f"eye: {weight}", (x,y), cv2.FONT_HERSHEY_PLAIN, 1.5, (255,255,255), 1)

  cv2.imshow("Video", frame)

  if cv2.waitKey(1) == ord("q"):
    break

cap.release()
cv2.destroyAllWindows()

### 실습2. 귀여운 눈 덮어쓰기

In [1]:
import cv2
import numpy as np
CROSS = 'images/IU.jpg'
eye_cascade = cv2.CascadeClassifier("cascade/haarcascade_eye.xml")

img = cv2.imread(CROSS)
left_eye = cv2.imread('images/left_eye.jpg')
right_eye = cv2.imread('images/right_eye.jpg')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
eyes = eye_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=4, maxSize=(50,50))

indices = np.argsort(eyes[:,0])
sorted_eyes = eyes[indices]

if len (eyes):
    for i,(x, y, width, height) in enumerate(sorted_eyes):
      if i%2 == 0:
        new_eye = right_eye
      else:
        new_eye = left_eye
      
      new_eye = cv2.resize(new_eye,(width,height))
      img[y:y+new_eye.shape[0], x:x+new_eye.shape[1]] = new_eye

cv2.imshow("img", img)        
cv2.waitKey(0)
cv2.destroyAllWindows()

(42, 42, 3)


### 동영상에 눈 덮어쓰기

In [2]:
# 얼굴인식
import cv2
eye_cascade = cv2.CascadeClassifier("cascade/haarcascade_eye.xml")
road_path = 'videos/person2.mp4'
cap = cv2.VideoCapture(road_path)
fps = cap.get(cv2.CAP_PROP_FPS)

while cap.isOpened():    
    ret, frame = cap.read()
    
    if not ret:
        break
    
    eyes = eye_cascade.detectMultiScale(frame, scaleFactor = 1.1, minNeighbors = 5, minSize = (20,20), maxSize=(200,200))

    if len (eyes):
        for i,(x, y, width, heigh) in enumerate(eyes):
            if i%2 == 0:
                new_eye = right_eye
            else:
                new_eye = left_eye
        
            new_eye = cv2.resize(new_eye,(width,height))
            frame[y:y+height, x:x+width] = new_eye
    
    cv2.imshow('video',frame)
    
    if cv2.waitKey(int(1000/fps)) == ord("q"):
        break

cv2.waitKey(0)
cap.release()
cv2.destroyAllWindows()


In [3]:
# %conda install pytorch torchvision torchaudio cpuonly -c pytorch

In [3]:
import cv2
from ultralytics import YOLO
# image = cv2.imread('images/singer.jpg')
# model = YOLO('yolo11n.pt') # initialize model
# model.predict(source=image, conf=0.5)

model = YOLO("yolo11n.pt")  # initialize model
results = model("images/IU.jpg")  # perform inference
results[0].show()  # display results for the first image


image 1/1 c:\Users\hsjin\git-test\opencv-practice\images\IU.jpg: 640x480 1 person, 388.0ms
Speed: 18.0ms preprocess, 388.0ms inference, 18.0ms postprocess per image at shape (1, 3, 640, 480)
